add help command.
desyncr/zpm-zsh pull request #12
Opened 2017-01-26 17:31 UTC by fennecdjay

again.
But this time against your HEAD.
sorry for the previous help PR.

2017-01-26 20:34 UTC, desyncr requested changes
Everything's looking good. One small nitpick though.

2017-01-26 20:34 UTC, desyncr commented on zpm.c
> +		usage();
Use (four) spaces rather than tabs for indentation.

2017-01-26 20:42 UTC, merged

2017-01-26 20:42 UTC, desyncr commented
Yay! Thank you so much @fennecdjay !

2017-01-26 20:44 UTC, fennecdjay commented
sorry for the *nitpick* (I didn't know this word). I'm glad I'm figuring out better the *feature branching* stuff.
If you provide more info on some issues, I'll be happy to help!!!

2017-01-26 20:57 UTC, desyncr commented
@fennecdjay Awesome! If you are up to it I'd be more than happy to add you as a zpm-zsh's collaborator. What that means is you'll have `push` access to the repository (be able to commit and merge to `master`) \*.

There are a few issues around and the TODO list for missing features. There is also [this](https://trello.com/b/TtXA4Ajz/zpm-zsh) Trello board for the project roadmap. Any idea and suggestion is greatly welcomed!

What do you think? Looking forward to it!

\* _Although, I usually work on `feature` branches and creating a PR for review, iterate on the given feedback and then merge the PR._

2017-01-27 09:47 UTC, fennecdjay commented
I'll d be glad to help !!!!

P.S.: it looks like the trello board for zpm-zsh is private, maybe you have to invite me or something like that for me to see it.

2017-01-27 14:38 UTC, desyncr commented
@fennecdjay Awesome. Trello board should be public now, I'll need you trello user so you're able to contribute to the board.

2017-01-27 19:24 UTC, fennecdjay commented
I've found the board, and I think you are now invited on [this](https://trello.com/b/nTRU3qpX/meet-people). this is just a stub, but maybe you can get my user from there.

2017-01-27 21:31 UTC, desyncr commented
@fennecdjay Added to the board! Welcome!

2017-01-27 21:33 UTC, fennecdjay commented
Thanks!