allow other repository host. fix #5
desyncr/zpm-zsh pull request #13
Opened 2017-01-26 21:47 UTC by fennecdjay

It just assumes that if there is only one slash in the path, plugin is to be found on github.

2017-01-26 22:12 UTC, desyncr requested changes
Conding conventions changes.

2017-01-26 22:12 UTC, desyncr commented on zpm.c
> +    if(!tmp)
Conding convention:

- space after `if`
- no spaces between `(`, `)`
- always use `{`, `}`

Ex: `if (!tmp) {`

2017-01-26 22:22 UTC, desyncr commented
There is a side effect we have to evalute that we're now able to install both `user/plugin` and `host/user/plugin`, example: `desyncr/watch` and `github.com/desyncr/watch`.

2017-01-26 23:07 UTC, fennecdjay commented on zpm.c
> +    if(!tmp)
I'm afraid I do not understand the second statement in the list. is it relevant to that piece of code?

2017-01-26 23:10 UTC, desyncr approved these changes
We're good to go!

2017-01-26 23:37 UTC, fennecdjay commented
There is still the side effect you mentionned to fix.
And also a segfault if you try something like:
```sh
zpm string_with_no_slash
```

2017-01-27 03:33 UTC, desyncr commented
Gonna take a further look tomorrow and merge.

2017-01-27 16:08 UTC, merged

2017-01-27 16:08 UTC, desyncr commented
Amazing! Thank you!