Add save command.
desyncr/zpm-zsh pull request #25
Opened 2017-01-30 20:49 UTC by fennecdjay

Here it is ;-)
It looks just fine to me.
---------

2017-01-31 00:11 UTC, fennecdjay commented
We're almost done!
I'd just like rmdir_r() to remove user directory if it is empty.

2017-01-31 12:40 UTC, desyncr commented
Nice! I'm gonna take a look tonight!

2017-01-31 16:45 UTC, desyncr requested changes
Some minor changes.

2017-01-31 16:45 UTC, desyncr commented on README.md
> +zpm remove user/plugin
Not actually necessary but to keep a unified syntax on the README.md and in general, it should quote the plugin name. ie: `zpm remove "user/plugin"`

2017-01-31 16:45 UTC, desyncr commented on zpm.c
> +        printf("zpm %s", entry);
Will need quotes on plugin name.

2017-01-31 16:45 UTC, desyncr commented on README.md
> +zpm save > .zpmrc
We probably will need to explain the workflow with an example. Ex:

Install some plugins:

    zpm "some/plugin"
    zpm "other/plugin"

Then you can persist your current configuration to be able to commit it into a dotfile repository:

    zpm save > ~/dotfiles/.zpmrc

Next time you'll only need to install them like so:

    source ~/dotfiles/.zpmrc

2017-01-31 19:57 UTC, desyncr commented on zpm.c
> +    printf("#!/bin/sh\n");
I believe there is no need for this.

2017-01-31 20:40 UTC, fennecdjay commented on zpm.c
> +    printf("#!/bin/sh\n");
Right. I just tought it was more correct.
Removing it.

2017-02-02 14:38 UTC, fennecdjay commented
Maybe you should rework the README.md, as you clearly know zpm's workflow better than I do.

2017-02-02 14:40 UTC, desyncr commented
Seems fair. I'll create another issue for the README.md

2017-02-02 14:44 UTC, desyncr commented
Last thing would be to add `remove` and `uninstall` to the list of available commands.

2017-02-02 14:55 UTC, desyncr commented
On a quick test it failed to `uninstall` the plugin directory. It seems it removed the `.git` directory though.

I also believe we could change terms: "remove" for unlinking/remove directory, and "disable" to remove plugin from listing. It's a small thing but it's best to get it correct the first time.

2017-02-02 18:50 UTC, fennecdjay commented
If you agree, I'll comment everything in rmdir_r(), and just use something like
```c
system("rm -r xxx")
```
so we get the functionnality, until I fix that function.

2017-02-02 19:01 UTC, desyncr commented
@fennecdjay I do agree. For now it'll suffice.

2017-02-02 23:38 UTC, fennecdjay commented
We can ignore Travis warning for now, as it complains about rake (?).
On my station it seems to work just fine.

2017-02-02 23:41 UTC, fennecdjay commented
Also, I see you created zpm-project organisation, so I suppose you expect next PR to be [there](https://github.com/zpm-project/zpm-zsh).

2017-02-03 00:35 UTC, fennecdjay commented
Oups...
Pushing the rigth thing now.

2017-02-03 00:37 UTC, desyncr commented
@fennecdjay There is a lot of comments and useful interactions, so let's keep it here until the final approval. Then we'll move to zpm-project. Sorry for the mess up but it has to be sooner or later :)

2017-02-03 00:42 UTC, fennecdjay commented
Very good to me. ;-)

2017-02-03 02:10 UTC, desyncr requested changes
One last thing.

2017-02-03 02:10 UTC, desyncr commented on zpm.c
> +/*
Remove all this commented out code.

2017-02-03 02:10 UTC, desyncr commented on zpm.t
> +    zsh-users/zsh-syntax-highlighting .*
We should probably add tests for this but for now I want to get this merged ASAP to avoid huge git conflicts.

2017-02-03 02:11 UTC, desyncr commented
One last thing then we can merge this. Once done you have to create a new PR in `zpm-project/zpm-zsh` repository.

2017-02-03 12:00 UTC, fennecdjay commented on zpm.t
> +    zsh-users/zsh-syntax-highlighting .*
Fine. reverting.

2017-02-03 12:18 UTC, fennecdjay commented
I'm waiting for your signal to either do more changes or create PR in zpm-project/zpm-zsh repository.

2017-02-03 12:18 UTC, desyncr approved these changes
We are done! Great job! Let's move it to `zpm-project/zpm-zsh` repository.

2017-02-03 12:19 UTC, fennecdjay commented
Great! doing it rigth now.

2017-02-03 12:23 UTC, desyncr commented
Also, remember to review https://github.com/zpm-project/zpm-zsh/pull/6

2017-02-03 12:24 UTC, fennecdjay commented
Sure thing!
Yet I have to figure out how to do so ;-)

2017-02-03 17:35 UTC, desyncr commented
Moved to https://github.com/zpm-project/zpm-zsh/pull/12

2017-02-03 17:35 UTC, closed without merging