Fix memory usage and add update command.
desyncr/zpm-zsh pull request #9
Opened 2017-01-18 12:25 UTC by fennecdjay

This PR improves memory usage and add a (simple) update command.
Thanks for the work.
let me know.

2017-01-18 21:47 UTC, desyncr commented
You are awesome. Thank you very much.

I'm gonna take a look tonight.

2017-01-24 14:31 UTC, desyncr requested changes
Looks good to me! Thanks a lot.

There is these two small things and we'll be ready to merge.

2017-01-24 14:31 UTC, desyncr commented on zpm.c
> +strcpy(command, "echo lol ");
Remove this.

2017-01-24 14:31 UTC, desyncr commented on zpm.c
> +
Add a "Updating plugins..." message around here.

2017-01-24 14:47 UTC, fennecdjay commented on zpm.c
> +strcpy(command, "echo lol ");
sorry about this one.

2017-01-24 14:51 UTC, fennecdjay commented
Great.
I give a try.

2017-01-24 14:55 UTC, fennecdjay commented
This might be ok now.

2017-01-24 15:13 UTC, desyncr commented
Cool thanks. Anyways from my side it doesn't seem to work as expected. It seems to only iterate over the first plugin listed, rather than over all of them.

2017-01-24 15:24 UTC, fennecdjay commented
My mistake.
my config was back to only one plugin, so I missed that.
I'll fix fix ASAP.

2017-01-24 15:29 UTC, desyncr commented
Don't worry, great work so far!

2017-01-25 10:20 UTC, fennecdjay commented
Now system is called for every installed plugin.
Also I updated the README to reflect current state.

2017-01-25 18:06 UTC, desyncr requested changes
We're getting there :+1: A few small changes.

2017-01-25 18:06 UTC, desyncr commented on zpm.c
> +    printf("Update plugins ...\n");
This `printf` should be before the `while` loop, not after it. Be sure it reads "Updating plugins...".

2017-01-25 18:06 UTC, desyncr commented on zpm.c
> +      strcpy(command, "cd ~/.zpm/plugins/");
Maybe we could add a `"Updating %s...", plugin_name`?

2017-01-25 18:06 UTC, desyncr commented
Looking forward to merge this! Great work!

2017-01-26 15:26 UTC, fennecdjay commented
This is better. I also fixed a bug when list is empty.
Let me know I you want individual plugin update message.

2017-01-26 20:30 UTC, desyncr requested changes
One final touch up and we're done! :D

2017-01-26 20:30 UTC, desyncr commented on zpm.c
> +      strcat(command, "; git pull");
Adding a print below this line would be the final touch up:

    printf("Updating %s...\n", plugin_name);

2017-01-26 20:32 UTC, fennecdjay commented on zpm.c
> +      strcat(command, "; git pull");
Done!!!

2017-01-26 20:35 UTC, desyncr commented on zpm.c
> +      strcat(command, "; git pull");
Awesome! Gonna merge now!

2017-01-26 20:37 UTC, merged